interface=eth0
listen-address=10.10.3.1
bind-interfaces
port=53
no-resolv
no-hosts
domain=demo.test
expand-hosts
dhcp-authoritative
dhcp-range=10.10.3.100,10.10.3.199,255.255.255.0,12h
dhcp-leasefile=/var/lib/intermasq-lab/demo/data/dnsmasq.leases
address=/router.demo.test/10.10.3.1
conf-file=/etc/intermasq-lab/devices/demo.conf
