interface=eth0
listen-address=10.10.2.1
bind-interfaces
port=53
no-resolv
no-hosts
domain=lab.test
expand-hosts
dhcp-authoritative
dhcp-range=10.10.2.100,10.10.2.199,255.255.255.0,12h
dhcp-leasefile=/var/lib/intermasq-lab/lab/data/dnsmasq.leases
address=/router.lab.test/10.10.2.1
conf-file=/etc/intermasq-lab/devices/lab.conf
