#!/bin/sh

LAB_ROOT=/var/lib/intermasq-lab
INTERMASQ_BIN=/usr/local/lib/intermasq
INTERNAL_PANEL_PORT=8081
LAB_ADMIN_USERNAME=admin
LAB_ADMIN_PASSWORD=intermasq-lab
LAB_DEMO_USERNAME=operator
LAB_DEMO_PASSWORD=operator-lab
