no-resolv
no-hosts
domain=demo.test
expand-hosts
dhcp-authoritative
dhcp-range=10.10.3.100,10.10.3.199,255.255.255.0,12h
address=/router.demo.test/10.10.3.1
conf-file=/var/lib/intermasq-lab/demo/conf/demo-devices.conf
conf-file=/var/lib/intermasq-lab/demo/conf/demo-options.conf
conf-file=/var/lib/intermasq-lab/demo/conf/demo-forwarder.conf
