no-resolv
no-hosts
domain=office.test
expand-hosts
dhcp-authoritative
dhcp-range=10.10.1.100,10.10.1.199,255.255.255.0,12h
address=/router.office.test/10.10.1.1
conf-file=/var/lib/intermasq-lab/office/conf/office-devices.conf
conf-file=/var/lib/intermasq-lab/office/conf/office-options.conf
conf-file=/var/lib/intermasq-lab/office/conf/office-forwarder.conf
