// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/status": {
            "get": {
                "summary": "Get service status",
                "tags": ["system"],
                "responses": {
                    "200": {"description": "Service status"}
                }
            }
        },
        "/api/login": {
            "post": {
                "summary": "Log in",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "JWT token"},
                    "401": {"description": "Invalid credentials"}
                }
            }
        },
        "/api/hosts": {
            "get": {
                "summary": "List static hosts",
                "tags": ["hosts"],
                "responses": {
                    "200": {"description": "Static hosts"},
                    "401": {"description": "Authentication required"}
                }
            },
            "post": {
                "summary": "Create or update a static host",
                "tags": ["hosts"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "200": {"description": "Host saved"},
                    "400": {"description": "Invalid host"},
                    "401": {"description": "Authentication required"}
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0-pre",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Intermasq API",
	Description:      "HTTP API for managing dnsmasq",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
